### ISSUE TITLE
Voting Session #2 - Approved Grants

### ISSUE THREAD

**Issue by nonfungibleab** [algorandfoundation/xGov#106]
We are pleased to confirm that 12 proposals have been directly approved by xGovs in Voting Session #2. They are:

#61 Chaintrail - Uncovering Algorand by Leander by @ChainTrail 
#70 Securing ASA Stats API high availability for the next 2 years by @ipaleka 
#71 ASA Stats Point in Time - tax reporting reference for US citizens by @ipaleka
#72 Algorand Inc structured selling dashboard by @papasotiriou 
#74 Notiboy Web3 Chat @Vidhyanandcs
#77 AlgoVerify by @algovado
#78 Evil Wallet - Asset Browser and Manager with Bulk Functions by @loafpickleWW
#83 Algo Community Collab - 3D Game NFTs by @madshapes-dev 
#84 Decentralized liquidity aggregator & lending platform by @grzracz @ErikHasselwander @BunsanMuchi @Zykoz
#86 Bonfire by @SilentRhetoric 
#87 Alright by @SilentRhetoric
#93 Community PVP Tournament by @madshapes-dev

Six proposals have been approved through the Reserve List method, introduced after voting session 1. 

#55 GoPlausible Multi-Chain milestone by @emg110 @sheghzo
#80 Open source concentrated liqudity AMM by @scholtz
#81 VoteCoin - DAO Liquidity by @scholtz
#85 MINTHOL.ART, the next-generation loyalty program and coupon platform (launchpad phase) by @solkimicreb
#89 Invoicing service by @scholtz
#90 AWallet scheduler by @scholtz

Congratulations to all of you! Next stop contracts. We will need your email address to begin the process.

**Comment by nonfungibleab** [comment]
Hello @solkimicreb - we need your email address to start contract comms.

**Comment by solkimicreb** [comment]
Hi Adriana!

My email address is ***@***.***

Thanks,
Bertalan

Adriana Belotti ***@***.***> ezt írta (időpont: 2023. dec.
15., P, 6:35):
