### ISSUE TITLE
Time of a submission deadline

### ISSUE THREAD

**Issue by scholtz** [algorandfoundation/xGov#21]
Hi, what is the deadline for submissions pls?

**Comment by nonfungibleab** [comment]
There are no deadlines; if a submission status is not in FINAL the week before we are set to create the voting session, it will remain in the queue. We can define when to archive old proposals later on, if they start to accumulate.

**Comment by ipaleka** [comment]
> There are no deadlines; if a submission status is not in FINAL the week before we are set to create the voting session, it will remain in the queue. We can define when to archive old proposals later on, if they start to accumulate.

In step 16 of the [Video Guide](https://youtu.be/BiqM8B8J8lM?t=262) voiceover says "Finally, the xGov team will request you to update the status to Final from Draft".

I've noticed OP has set his proposals' statuses to Final without any intervention from the xGov team.

Are we all supposed to set the status to Final by ourselves?

**Comment by ipaleka** [comment]
> Are we all supposed to set the status to Final by ourselves?

@nonfungibleab
