### ISSUE TITLE
Final call for xGov Voting Session #1 - Proposal Status

### ISSUE THREAD

**Issue by nonfungibleab** [algorandfoundation/xGov#45]
Hello to all proposers, we are preparing to create our first xGov voting session. 

Proposals with `Status: Final` at midnight Singapore Time on Sunday, 16 July 2023, will be included in xGov Voting Session #1. 
Proposals with `Status: Draft` will be carried over and remain open for discussion.

**Is your proposal ready?**

You can change the status of your proposal at any time. Please ensure you have discussed your proposal with the community and answered questions here and on the [Algorand Forum](https://forum.algorand.org). 

**Timeline for Voting Session #1**
[Confirmed] 16 Jul 2023 Proposed `Status: Final` cut-off date
[Proposed] 20 Jul 2023  Voting Session test with real data on testnet
[Proposed] 28 Jul 2023  Voting Session #1 uploaded to mainnet
[Proposed] 01 Aug 2023 Voting Session #1 opens
[Proposed]  31 Aug 2023 Voting Session #1 closes

[Proposed] Date may be changed. This is an indication for planning purposes.
[Confirmed] Date is confirmed.

**Comment by AtticusLScott** [comment]
Hi.

Folks and @nonfungibleab, I read this comment  from the xGov readme file:

"For example, xGov Voting Session 1 (Term Pool 1) will be in August 2023, and only proposals that fit the criteria and have status set to 'final' by COB Singapore time on 15 August 2023 will be included."

I thought the deadline to submit the proposal was end of July. I already submitted a proposal that I think it would be interesting for you and the community. It is https://github.com/algorandfoundation/xGov/pull/52 

Please, Can you consider this proposal for this the August voting session?

**Comment by nonfungibleab** [comment]
Here's the confirmed timeline for xGov Voting Session 1

Timeline for Voting Session https://github.com/algorandfoundation/xGov/pull/1
[Confirmed] 16 Jul 2023 Proposed Status: Final cut-off date
[Confirmed] 20 Jul 2023 Voting Session test with real data on testnet
[Confirmed] 28 Jul 2023 Voting Session https://github.com/algorandfoundation/xGov/pull/1 uploaded to mainnet
[Confirmed] 01 Aug 2023 Voting Session https://github.com/algorandfoundation/xGov/pull/1 opens
[Confirmed] 31 Aug 2023 Voting Session https://github.com/algorandfoundation/xGov/pull/1 closes

[Proposed] Date may be changed. This is an indication for planning purposes.
[Confirmed] Date is confirmed.

**Comment by nonfungibleab** [comment]
Hi @AtticusLScott will see if possible.

**Comment by AtticusLScott** [comment]
Thank you @AtticusLScott . Please, let us know if you need anything from us!

**Comment by nonfungibleab** [comment]
> Hey! Please clarify the finalizing process. I submitted our proposal on June 20. Since then no comments or anything has been received. At the same time proposals, that came after ours, are finalized and merged. What have we done wrong or what should we do to make it completed and participate in the voting?
> 
> #35

Read the start of this issue, it has the timeline for the first voting session.
From what I can see, proposal  #35 `Status = Draft`.
Only proposals with `Status = Final` are included in voting sessions. 
For voting session 1 the status deadline was 16 July, as specified at the top post in this issue. 
Yours can be added to the next Voting Session, if `Status = Final` at the cut-off date for Voting Session 2, yet to be defined.
