### ISSUE TITLE
Why there is no change in status of my PR

### ISSUE THREAD

**Issue by emg110** [algorandfoundation/xGov#60]
My PR: https://github.com/algorandfoundation/xGov/pull/55
Has been there for weeks and there is no change and no merger! May I ask for the reasons?

**Comment by nonfungibleab** [comment]
It might be better to comment on your PR and ask for clarifications there @emg110 instead of opening an issue :)
Nothing happens in between voting sessions, unless you actively engage the community, sharing your link and asking for feedback.

**Comment by emg110** [comment]
Thank you so much, this was an old one I forgot to close in fact! all good!
