### ISSUE TITLE
Hi im @Salbiero would you please reply me! thanks

### ISSUE THREAD

**Issue by Salbiero** [algorandfoundation/xGov#63]
Hello, I'm Santiago Albiero, I have a proposal in xgov from algorand. My proposal is #50 "sureblocks" and I would like to know why it does not change to the finalized status, so that it can be voted on to receive support

**Comment by nonfungibleab** [comment]
All the dates in your proposal are in the past. Have you already developed everything? You might want to review your proposal before the next voting session or people might not vote to support it because "what is happening and when" is unclear.

**Comment by Salbiero** [comment]
Hello, yes I have been working on the website of the site.
The website is developed is sureblocks.io and I added it to the list. Also update the roadmap dates.

Also, github tells me that I have a required action, and I don't know what to do, I'll send you a screenshot.
![github sure](https://github.com/algorandfoundation/xGov/assets/139647954/1212782c-42cf-4dea-b484-3eb63128b316)

**Comment by Salbiero** [comment]
What I don't know is why it remains in the poolrequest within the 15 open ones... and... it goes to the 43 closed ones.

**Comment by nonfungibleab** [comment]
I don't understand what you mean.

**Comment by Salbiero** [comment]
ok ok.
