### ISSUE TITLE
xGov Voting Session 2: Reddit AMA

### ISSUE THREAD

**Issue by fredestante** [algorandfoundation/xGov#94]
Hi xGov Proposers,

This is an open invitation for the “xGov Proposer Reddit MEGA AMA” to be held on Thursday, November 9th at https://www.reddit.com/r/AlgorandOfficial

This event will be an opportunity for the community to ask questions to any and all xGov proposers to help them decide how to fulfill their xGov voting duties.

**The structure of the AMA**:

- AMA to be posted on November 9th at 1pm UTC to start collecting questions form the community
- AMA to start on November 9th at 4pm UTC - this is when projects start responding to community questions (please don't answer before the live time!)
- Duration: 2 hours (4pm to 6pm UTC)
- Projects can continue to answer and engage with the community once the 2h period is over, but all participants are encouraged to be active during this time slot.

**How to sign up as a proposer**:

You must respond to this github issue from the same account as you sent your xGov proposal with the following information:

- Name: Name of your project
- Description: Short description of your project (500 characters max)
- Link: One link to your project (website, social media, etc)
- Submission Link: The link to your xGov Proposal
- Amount Requested: The amount requested in your xGov Proposal
- Reddit username: Reddit usernames of everyone from your team that will answer questions from the community. These accounts will receive a special flair to indicate which project they are affiliated with.

**Deadlines**:

The deadline to sign up for the Reddit AMA is November 7th at 8pm UTC. This is a hard deadline and projects who fail to meet the deadline will not be included.

**AMA logistics**:

The AMA on Reddit will contain all projects that sign up in this issue, and they will be added to the post in they order they are registered here.

**Rules**:

Review all the rules of our sub before making your comments. The rules are available on the sidebar at https://www.reddit.com/r/AlgorandOfficial.

**Comment by kylebeee** [comment]
Hey! Would love to participate

Name: Akita
Description: Community / Creator platform (including staking, subscriptions & eventually socialFi)
Link: https://akita.community
Submission Link: https://github.com/algorandfoundation/xGov/pull/53
Amount Requested: 300000
Reddit username: r/akita_inu_official

**Comment by Salbiero** [comment]
Name: SUREBLOCKS.IO
Description: The proposal is designed to make the products that people use daily (such as clothes or food or electronics) so that they can contain an algorand nft and authenticate the originality of these products, and thus generate more users for the algo network and contribute to mass adoption.
Companies that accept this have a solution to the problem of piracy, smuggling and even against theft.
Each product will be traceable, it can be segmented by country to avoid contraband and also the nft will certify the authenticity of the product.
We already have serious approaches with wineries in Argentina, to incorporate nft to each bottle of wine. We have presented the proposals and we are starting to put together a dapp.
Sureblocks will be a symbol of safety for people. It could even be incorporated into medicines.
Link: https://www.sureblocks.io
Submission Link: https://github.com/algorandfoundation/xGov/blob/90f91c71293d17cf1a53d7779b440909f2adcaa5/Proposals/xgov-x.md
Amount Requested: 26OOO USD/ALGO
Reddit username: u/santialbiero

**Comment by SilentRhetoric** [comment]
**Name:** Bonfire🔥
**Description:** Burn ASAs by throwing them into the Bonfire--a standard, permissionless, and verifiable way to take ASAs out of circulation forever through an interface for standard ARC-54: ASA Burning App.
**Link:** [https://asa-bonfire.netlify.app](https://asa-bonfire.netlify.app)
**Submission Link:** [https://github.com/algorandfoundation/xGov/pull/86/files](https://github.com/algorandfoundation/xGov/pull/86/files)
**Amount Requested:** 10,000A (minimum request)
**Reddit Username:** @SilentRhetoric

**Comment by SilentRhetoric** [comment]
**Name:** Alright
**Description:** Alright is a peer-to-peer agreements app to safely exchange goods & services with anyone through decentralized escrow.

Alright enables two people to lock in an agreement to buy or sell something remotely, secure the deal with collateral as a security deposit, and release the payment when they are both ready. Alright is for any transaction that comes with some counterparty risk of non-performance, and it is faster, easier, and cheaper than using traditional middleman escrow services.
**Link:** [https://alright.app](https://alright.app)
**Submission Link:** [https://github.com/algorandfoundation/xGov/pull/87/files](https://github.com/algorandfoundation/xGov/pull/87/files)
**Amount Requested:** 100,000A
**Reddit Username:** @SilentRhetoric

**Comment by Vidhyanandcs** [comment]
Hey! Would love to participate

Name: Notiboy
Description: Notiboy web3 chat application
Link: https://notiboy.com/
Submission Link: https://github.com/algorandfoundation/xGov/pull/74
Amount Requested: 30,000
Reddit username: u/semanticweb

**Comment by scholtz** [comment]
Name: Ludo, Everyday Algonaut
Description: VoteCoin - GitHub tools
Link: https://www.vote-coin.com
Submission Link: #79
Amount Requested: 120,000A
Reddit username: u/LudovitScholtz

**Comment by scholtz** [comment]
Name: Ludo, Everyday Algonaut
Description: Open source concentrated liqudity AMM
Link: https://discord.com/invite/Z3yQkU3kbT
Submission Link: #80
Amount Requested: 300,000A (2 milestones)
Reddit username: u/LudovitScholtz

**Comment by scholtz** [comment]
Name: Ludo, Everyday Algonaut
Description: VoteCoin - DAO Liquidity
Link: https://www.vote-coin.com
Submission Link: #81
Amount Requested: 32,000A
Reddit username: u/LudovitScholtz

**Comment by scholtz** [comment]
Name: Ludo, Everyday Algonaut
Description: Prague community meetups
Link: https://docs.google.com/presentation/d/1BsLna79fNi6RYk3R-Tgl6R15kwiUBq4ULJalsnPF6UI/edit?usp=sharing
Submission Link: #82
Amount Requested: 200,000A
Reddit username: u/LudovitScholtz

**Comment by scholtz** [comment]
Name: Ludo, Everyday Algonaut
Description: Invoicing service
Link: https://www.a-wallet.net
Submission Link: #89 
Amount Requested: 100,000A
Reddit username: u/LudovitScholtz

**Comment by scholtz** [comment]
Name: Ludo, Everyday Algonaut
Description: AWallet scheduler
Link: https://www.a-wallet.net
Submission Link: #90 
Amount Requested: 60,000A
Reddit username: u/LudovitScholtz

**Comment by ipaleka** [comment]
- Name: Securing ASA Stats API high availability for the next 2 years
- Description: ASA Stats API makes all the ASA Stats website's functionalities available to any development team or individual. We are using this opportunity to allow the continuation of the API development, as well as its improvement and administration for the next 2 years. On top of that, this proposal will allow us to provide a tenfold increase in our API bandwidth and high availability with an uptime equal to or very close to 100%.
- Link: https://www.asastats.com
- Submission Link: https://github.com/algorandfoundation/xGov/blob/main/Proposals/xgov-70.md
- Amount Requested: 42000
- Reddit username: u/hopemeetme, u/kerrilija, u/Unohim, u/AlgoRhythMatic

**Comment by ipaleka** [comment]
- Name: Milestone 2 - ASA Stats tax reporting reference
- Description: The ASA Stats team will develop and deploy endpoints that will be used for creating CSV files ready to be imported into crypto tax software. Such CSV files will contain all the relevant transactions for a user's selected period. ASA Stats aims to prepare endpoints for the majority of available tax software. In the testing phase, the main focus will be on the most popular software like Crypto.com Tax, Koinly, CoinTracker, and CoinTracking.
- Link: https://www.asastats.com
- Submission Link: https://github.com/algorandfoundation/xGov/pull/71
- Amount Requested: 55000
- Reddit username: u/hopemeetme, u/kerrilija, u/Unohim, u/AlgoRhythMatic

**Comment by LoafPickleWW** [comment]
**Name:** Evil Wallet: Asset Browser and Manager with Bulk Functionality (Rebrand incoming)
**Description:** An easy way to browse, select, and manage your assets. Imagine the bulk functionality support already within Evil Tools (Rebrand Incoming), with the ability to select each asset instead of Copy/Pasting ASA IDs.
**Link:** https://evil-tools.thurstober.com/
**Submission Link:** https://github.com/algorandfoundation/xGov/pull/78
**Amount Requested:** 15,000A 
**Reddit Username:** u/loafpickle

**Comment by madshapes-dev** [comment]
**Name:** Algo Community Collab - 3D Game NFTs
**Description:** Ever imagined Al Goanna, COOP or MNGO as a game character in Cosmic Champs game PVP battle arena? So did we! There is plenty of Algorand projects that are great fit for our game setting. Unfortunately it's cost prohibitive for us to do such fun collabs as making a fully animated, game ready 3d NFT takes lots of resources. If funded, we will create and distribute these NFTs for free to help promote Algorand projects to our players and our game to the Algorand community. win-win
**Link:** https://discord.gg/cGCjvhNbBR
**Submission Link:** https://github.com/algorandfoundation/xGov/pull/83
**Amount Requested:** 30,000A
**Reddit username:** u/cc-simon , u/cosmicchamps

**Comment by madshapes-dev** [comment]
**Name:** Community PVP Tournament
**Description:** Gaming and tournament play is a powerful vehicle for attracting new users. A free entry tournament with BIG prize pool allows us to promote to and attract users from wider crypto ecosystem as well as more conventional gaming audience. Our game requires Algorand wallet, so each new participant from these communities will directly translate into a new Algorand user. We've hosted multiple tournaments in the past with very positive results.
**Link:** https://discord.gg/cGCjvhNbBR
**Submission Link:** https://github.com/algorandfoundation/xGov/pull/93
**Amount Requested:** 20,000A
**Reddit username:** u/cc-simon , u/cosmicchamps
